name: Sync Tasks to Google Calendar

on:
  push:
    paths:
      - 'notes/**'
  schedule:
    - cron: '0 22 * * *'  # 毎日12:00 JST（= 3:00 UTC）

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run task sync
        run: npm run sync
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}